### ISSUE TITLE
O que pretende fazer?

### ISSUE THREAD

**Issue by LeoNero** [drodrigo/graphql-adventures#1]
Tô querendo aprender GraphQL também... se quiser passar um desafio ou fazer algo juntos :D

**Comment by itsdaiego** [comment]
Tava pensando em construir uma app simples pra explorar as funcionalidades do GraphQL, mas não tenho nada em mente haha, assim que decidir ou se você tiver uma ideia também bora fazer isso juntos sim :+1: 

Valeu @LeoNero

**Comment by LeoNero** [comment]
Pô também tô sem ideias kk talvez uma api simples de corrida kk tipo, tem um Usuário que tem o cadastro dele e tals, daí ele tem associado a ele corridas. Daí cada Corrida tem suas propriedades também kk

E daí um app React usando Apollo ou Relay

**Comment by itsdaiego** [comment]
Topo, gostei da ideia inicial... eu vou dar uma olhada em projetos de exemplo pra construir um app em node, eu não manjo de react mas topo aprender também (juntar o útil ao agradável... why not!?) 

Eu pensei em pegar alguma api pública e o servidor apenas iria interpretar a query de consulta, pegar os dados nessa api pública e retornar pro client.... assim nós não nos preocupamos com essa parte.

=) Quando eu achar uma API que sirva eu vejo como começar e falo aqui.

Vou te adicionar como contribuidor tbm, ai quando você quiser contribuir pode commitar a vontade  haha (mas lembre-se do filme do homem aranha... :stuck_out_tongue: )

Valeu!

**Comment by LeoNero** [comment]
Opaaa beleza :D

**Comment by LeoNero** [comment]
Se tiver vontade de fazer em outra linguagem (Go, Elixir, Clojure) ao inves de JS... mas só sugestão mesmo kk

**Comment by itsdaiego** [comment]
Haha vou deiaxr em Node por enquanto pra focar o aprendizado em uma coisa só ;)

**Comment by itsdaiego** [comment]
@LeoNero  como eu esou um cara pra lá de criativo vou usar a API do github mesmo: https://developer.github.com/v3/

Vou começar a criar o server e implementar um exemplo  de consulta, vou focar 0% no client por enquanto ;) 

Por fim vou tentar fazer depois uma lista de coisas a serem implementadas então se você tiver interesse 


vlw!!!

**Comment by felquis** [comment]
@drodrigo da uma olhada em como o [react-universally](https://github.com/ctrlplusb/react-universally) faz setup para usar React :)

**Comment by itsdaiego** [comment]
Oloko @felquis  =P não conhecia, valeu!!
